__author__ = 'mauricio'

from django.conf.urls import patterns, url

urlpatterns = patterns('web.views',
                       url(r'^$', 'renderPages'),
                       url(r'^register/$', 'registerBusiness', name='register'),
                       url(r'^registerAjax/$', 'registerBusinessAjax', name='registerB'),
                       url(r'^registerUserAjax/$', 'registerUserAjax', name='registerU'),
                       url(r'^request_coupon/', 'couponsForm', name="request_coupon"),
                       url(r'^welcome/', 'mobile_welcome', name="mobile_welcome"),
                       url(r'^partner/(?P<name>[-\w]+)$', 'mobile_partner', name='mobile_partner'),
                       url(r'^(?P<url_name>[-\w]+)$', 'renderPages', name='render'),
                       url(r'^modules/$', 'renderModules', name='modules'),
                       url(r'^content/(?P<page_number>\d+)$', 'addContent', name='content'),
                       url(r'^addForm/$', 'addForm', name='addForm'),
                       url(r'^user/js/utils_sys$', 'userUtils'),
                       url(r'^comment/report$', 'report_comment'),
                       url(r'^user/welcome', 'create_user_welcome', name='create_user_confirm'),
                       url(r'^user/confirm', 'remoteConfirm', name='remote-confirm'),
                       url(r'^user/register$', 'userRegister', name="register-user"),
                       url(r'^user/re-send-activation-mail$', 'reSendActivationMail'),
                       url(r'^user/register/checkout/email/$', 'checkout_email', name='checkout_email'),
                       url(r'^user/register/confirm/(?P<user_id>\d+)$', 'registerConfirm'),
                       url(r'^user/login$', 'userLogin'),
                       url(r'^user/logout$', 'userLogout', name="goodbye"),
                       url(r'^user/logout/(?P<path>[-\w]+)$', 'userLogoutRefresh', name="goodbyeback"),
                       url(r'^user/newpassword$', 'newPassword', name='newPassword'),
                       url(r'^user/reset$', 'reset_password', name='reset_password'),
                       url(r'^user/reset-email$', 'reset_email_password', name='reset_email_password'),
                       url(r'^user/login/ajax$', 'userLoginAjax', name='userLoginAjax'),
                       url(r'^detour/js/tiny.js$', 'tiny'),
                       url(r'^bring-detourmaps/$', 'bring_detourmaps', name="bring"),
                       url(r'^faq/$', 'faq', name="faq"),
                       url(r'^privacy-policy/$', 'privacy', name="privacy"),
                       url(r'^terms-and-conditions/$', 'terms', name="terms"),
                       url(r'^upload/$', 'uploadImage', name='upload'),
                       url(r'^posts/$', 'get_active_posts', name='posts'),
                       url(r'^media-kit/$', 'media_kit', name='media_kit'),
                       url(r'^media-kit/file/$', 'media_kit_file', name='media_kit_file'),
                       url(r'search-business/$', 'searchBusiness', name='search-business'),
                       url(r'share-url/$', 'shareQRUrl', name='share-qr'),
                       url(r'bookmarklet/$', 'bookmarklet', name='bookmarklet'),
                       url(r'contact_remote/$', 'contact_us', name='contact_us'),
)